FROM node:20-alpine

RUN addgroup -S kitchen-kabinet-front && adduser -S podman-kabinet -G kitchen-kabinet-front

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

RUN chown -R podman-kabinet:kitchen-kabinet-front /app

USER podman-kabinet

EXPOSE 5173

CMD ["npm", "run", "dev"]
