services:
  backend:
    build: ./backend
    container_name: meal-ticket-backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env
    stdin_open: true
    tty: true

  frontend:
    build: ./frontend
    container_name: meal-ticket-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - ./frontend/.env
    stdin_open: true
    tty: true
