services:
  meal-ticket:
    build: .
    container_name: meal-ticket
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    stdin_open: true
    tty: true
    environment:
      VITE_MEALTICKET_USER: ${MEALTICKET_USER}
      VITE_MEALTICKET_PASSWORD: ${MEALTICKET_PASSWORD}
